# Generated by Django 3.2.5 on 2021-07-11 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=256)),
                ('stock_exchange', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=16)),
                ('trading_date', models.DateField()),
                ('reference_price_vnd', models.IntegerField()),
                ('value_diff_vnd', models.IntegerField()),
                ('percentage_diff', models.IntegerField()),
                ('close_vnd', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('open_vnd', models.IntegerField()),
                ('highest_vnd', models.IntegerField()),
                ('lowest_vnd', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thade.company')),
            ],
        ),
    ]
