# Generated by Django 3.2.5 on 2021-07-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='trading_date',
            new_name='utc_trading_date',
        ),
    ]
