# Generated by Django 3.2.5 on 2021-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0002_rename_trading_date_record_utc_trading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rid',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='utc_trading_date',
            field=models.DateTimeField(),
        ),
    ]
