# Generated by Django 3.2.5 on 2021-07-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0004_auto_20210713_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('fee', models.FloatField()),
                ('deploy_date', models.DateTimeField()),
                ('stocks_per_trade', models.IntegerField()),
                ('algorithm', models.CharField(max_length=256)),
                ('investment_vnd', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thade.company')),
            ],
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_vnd', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('signal', models.IntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Hold'), (-1, 'Cannot afford to Buy'), (-2, 'Not enough stocks to Sell'), (0, 'Invalid signal')], default=0)),
                ('all_time_min_balance_vnd', models.IntegerField()),
                ('all_time_max_balance_vnd', models.IntegerField()),
                ('control_balance_vnd', models.IntegerField()),
                ('control_stocks', models.IntegerField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thade.bot')),
                ('last_updated_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='thade.record')),
            ],
        ),
    ]
