# Generated by Django 3.2.5 on 2021-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0005_bot_botlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botlog',
            old_name='all_time_max_balance_vnd',
            new_name='all_time_max_total_vnd',
        ),
        migrations.RenameField(
            model_name='botlog',
            old_name='all_time_min_balance_vnd',
            new_name='all_time_min_total_vnd',
        ),
        migrations.AlterField(
            model_name='bot',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='signal',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('NOT_BUY', 'Cannot afford to Buy'), ('NOT_SELL', 'Not enough stocks to Sell'), ('ERR', 'Invalid signal')], default='ERR', max_length=16),
        ),
    ]
