# Generated by Django 3.2.5 on 2021-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0006_auto_20210722_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlog',
            name='log_str',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
