# Generated by Django 3.2.5 on 2021-07-25 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0008_alter_botlog_log_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_fetched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 3, 30, 57, 106348, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
