# Generated by Django 3.2.5 on 2021-07-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0009_company_last_fetched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='last_fetched',
            new_name='last_records_fetched',
        ),
    ]
