# Generated by Django 3.2.5 on 2021-07-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0010_rename_last_fetched_company_last_records_fetched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='state',
            new_name='is_active',
        ),
    ]
