# Generated by Django 3.2.5 on 2021-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0012_auto_20210725_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlog',
            name='balance_vnd',
        ),
        migrations.RemoveField(
            model_name='botlog',
            name='control_balance_vnd',
        ),
        migrations.AddField(
            model_name='botlog',
            name='control_decimal_balance_vnd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botlog',
            name='decimal_balance_vnd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botlog',
            name='all_time_max_total_vnd',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='all_time_min_total_vnd',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
