# Generated by Django 3.2.5 on 2021-07-27 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0013_auto_20210726_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='records_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 2, 17, 7, 580480, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
