# Generated by Django 3.2.5 on 2021-07-27 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0015_remove_bot_records_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_records_fetched',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 4, 43, 59, 821514, tzinfo=utc)),
        ),
    ]
