# Generated by Django 3.2.5 on 2021-07-27 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0016_alter_company_last_records_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_records_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
