# Generated by Django 3.2.5 on 2021-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thade', '0017_alter_company_last_records_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlog',
            name='signal',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('NOT_BUY', 'Cannot afford to Buy'), ('NOT_SELL', 'Not enough stocks to Sell'), ('INVEST', 'Invest'), ('WITHDRAW', 'Withdraw'), ('ERR', 'Invalid signal'), ('DEPLOY', 'Deployed')], default='ERR', max_length=16),
        ),
    ]
